services:

    proxy:
      build:
        context: ../
        dockerfile: ./deploy/nginx/Dockerfile
      container_name: nginx
      hostname: nginx
      ports:
        - '${PROXY_PORT:-8081}:80'
      networks:
        - network

    backend-proxy:
      build:
        context: ../
        dockerfile: ./deploy/backend-proxy/Dockerfile
      container_name: backend-proxy
      hostname: backend-proxy
      networks:
        - network

    backend:
      build:
        context: ../
        dockerfile: ./deploy/php/Dockerfile
      networks:
        - network

    frontend:
      build:
        context: ../
        dockerfile: ./deploy/frontend/Dockerfile
      container_name: frontend
      hostname: frontend
      networks:
        - network

    postgres:
      image: postgres:alpine
      environment:
        POSTGRES_DB: ${POSTGRES_DB:-postgres}
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      ports:
        - '5432:5432'
      networks:
        - network

networks:
  network:

volumes:
  pgdata: